### ISSUE TITLE
Issuing scammer warning to moderators

### ISSUE THREAD

**Issue by MrHash** [PhABC/antiScamBot_slack#12]
In the event that a scammer posts an ETH or BTC address, it could be an alternative idea to message moderators with the scammers account name, rather than post a loud public message in the channel.

**Comment by PhABC** [comment]
I would rather not spam the moderators too much, but perhaps simply send a message to the person writing the address saying their message was deleted because it contained an address? The idea behind the public message was to make sure other users were aware that it was fake or to remind them to not trust addresses

**Comment by MrHash** [comment]
Sure, I understand. Personally i would like my channel to be calm and not announce scammers too loudly, but make admins/mods aware. If there are many attacks then the channel could get noisy. Perhaps we can work on making some of these settings configurable.

**Comment by PhABC** [comment]
That's totally fair. Perhaps we could do ; 

+ Send a private message to user saying they shouldn't post this
+ Warn admins/mods if the user tries to share >= 5 times (if the user is spamming). 

Discrete, doesn't spam the mods/admins all the time when people post stuff by mistake, but will still warn them if someone is spamming addresses.

**Comment by MrHash** [comment]
yes sounds good, although maybe a configurable threshold? for some, twice is spamming for others 5 is too much.

**Comment by PhABC** [comment]
Yep, sounds good

**Comment by PhABC** [comment]
Progress made ; 

Created an #scambot-internal channel where the bot posts stuff, like deleted messages, new users, etc. Will add posting ETH addresses soon, so user will be warned privately and team admins (and some mods) will be able to see the messages containing the ETH that was deleted.

**Comment by PhABC** [comment]
Implemented ; 

ETH addresses don't trigger a warning, instead the message is posted in #scambot-internal and a warning is sent via DM to the user at fault. #scambot-internal needs to be a private channel where the bot is present.
