### ISSUE TITLE
Add configurable list of URLs to auto-delete

### ISSUE THREAD

**Issue by philipcmonk** [PhABC/antiScamBot_slack#2]
Would be nice to be able to add specific URLs that are banned from a Slack.  Specifically, on the Numerai Slack, scammers have been posting n-u-m-e-r-a-i.t-e-c-h (without the hyphens), which is a look-alike of the Numerai website that asks for your private keys.

**Comment by PhABC** [comment]
What about a white list instead? Scammers always come with new domains, so might be easier to whitelist some websites and delete everything else.

What do you think?

**Comment by philipcmonk** [comment]
The problem is that we don't want to limit links to just a few urls.  What if we block all domains that are similar to a few specified domains, where "similar" could be a combination of a regex and a hamming distance check (if the part before the TLD is 3 or fewer changes away from the real domain, for example).

**Comment by PhABC** [comment]
Yeah that could work, although people will always find workaround. What I was thinking was that if someone post from unknown domain, they get a private message explaining they should ask a mod to whitelist the website. Could add a bot function that whitelist it.

**Comment by PhABC** [comment]
Feature added with commit 46a285236320c9226e18ac087ea96436abfce3b4
