### ISSUE TITLE
Add warning about posting private keys

### ISSUE THREAD

**Issue by Shalmezad** [PhABC/antiScamBot_slack#4]
Would be nice if [similar to how public ETH/BTC keys are filtered](https://github.com/PhABC/antiScamBot_slack/blob/master/plugins/AntiScam.py#L278), if there was a filter for private keys with a friendly reminder to the poster that private keys should *never* be shared with anyone.

**Comment by PhABC** [comment]
That's a really good idea! Will look into it soon.

**Comment by PhABC** [comment]
Added with commit eb487db0b17b7f9dcf8ce7616710470f3ae6a823
