### ISSUE TITLE
Errors running bot

### ISSUE THREAD

**Issue by MrHash** [PhABC/antiScamBot_slack#9]
Hi i get the following errors running the bot. Please advise.

```
Error : 
'announcements'
```

```
Error : 
'members'
```

**Comment by MrHash** [comment]
created channels and no errors now

**Comment by PhABC** [comment]
Hello,

The default Welcome message assumes that the #announcements channel exists. You can modify the Welcoming message by editing the Welcome.txt file. Let me know if that fixes it!

**Comment by PhABC** [comment]
Ah, just saw your last reply. Glad you found a solution :).

**Comment by MrHash** [comment]
Dude, great work. Much respect and thanks.

**Comment by PhABC** [comment]
Thank you!
